services:
  - type: web
    name: scraping-python
    env: python
    pythonVersion: 3.11.9
    plan: starter
    buildCommand: pip install --no-cache-dir -r requirements.txt && playwright install --with-deps chromium
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
